<?php

namespace App\Http\Controllers\Api\V1\Admin;

use App\Http\Controllers\Controller;
use App\Models\ManufacturingProduct;
use App\Models\ManufacturingProductCategory;
use App\Models\ManufacturingProductPattern;
use App\Models\ManufacturingPatternFabricWidth;
use App\Models\FabricWidth;
use App\Models\RawMaterial;
use App\Models\Task;
use App\Models\Product;
use App\Models\ProductCombination;
use App\Http\Requests\Api\V1\Admin\StoreManufacturingProductRequest;
use App\Http\Requests\Api\V1\Admin\UpdateManufacturingProductRequest;
use App\Http\Resources\Api\V1\AdminManufacturingProductResource;
use App\Http\Resources\Api\V1\AdminManufacturingCategoryResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

class AdminManufacturingProductController extends Controller
{
    protected array $withRelations = [
        'category.defaultTasks',
        'tasks',
        'subsidiaryMaterials',
        'stitchingMaterials',
        'patterns.fabricWidth',
        'patterns.patternFabricWidths.fabricWidth',
        'patterns.subsidiaryMaterials',
        'patterns.tasks',
        'frontendProduct',
        'frontendCombination',
    ];

    /**
     * Display a paginated list of manufacturing products.
     */
    public function index(Request $request): JsonResponse
    {
        $query = ManufacturingProduct::with($this->withRelations);

        if ($request->filled('search')) {
            $search = trim($request->input('search'));
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('code', 'like', "%{$search}%");
            });
        }

        if ($request->filled('category_id')) {
            $query->where('manufacturing_product_category_id', $request->input('category_id'));
        }

        if ($request->filled('status')) {
            $query->where('status', $request->input('status'));
        }

        $perPage = (int) $request->input('per_page', 15);
        $products = $query->latest('id')->paginate($perPage);

        return response()->json([
            'success' => true,
            'data' => AdminManufacturingProductResource::collection($products->getCollection()),
            'meta' => [
                'current_page' => $products->currentPage(),
                'last_page' => $products->lastPage(),
                'per_page' => $products->perPage(),
                'total' => $products->total(),
            ],
        ]);
    }

    /**
     * Get lookup options for creating/editing manufacturing products.
     */
    public function options(Request $request): JsonResponse
    {
        $activeCategories = ManufacturingProductCategory::where('status', true)->with('defaultTasks')->orderBy('name')->get();
        $availableTasks = Task::where('status', true)->orderBy('id')->get();
        $fabricWidths = FabricWidth::where('status', true)->orderBy('value', 'asc')->get();

        $subsidiaryMaterials = RawMaterial::active()
            ->orderBy('name')
            ->get();

        $stitchingMaterials = RawMaterial::active()
            ->orderBy('name')
            ->get();

        $storefrontProducts = Product::where('is_active', true)->select('id', 'title', 'sku')->orderBy('title')->get();

        $productId = $request->input('product_id');
        $storefrontCombinations = $productId
            ? ProductCombination::where('product_id', $productId)->where('is_active', true)->get()
            : collect();

        // Generate next sequential product code preview
        $year = date('Y');
        $latest = ManufacturingProduct::where('code', 'like', "MP-{$year}-%")->latest('id')->first();
        $seq = 1;
        if ($latest) {
            $parts = explode('-', $latest->code);
            $seq = ((int) end($parts)) + 1;
        } else {
            $latestId = ManufacturingProduct::max('id') ?? 0;
            $seq = $latestId + 1;
        }
        $autoGeneratedCode = "MP-{$year}-" . str_pad($seq, 4, '0', STR_PAD_LEFT);

        $packagingMaterials = RawMaterial::active()
            ->orderBy('name')
            ->get();

        $lengthGroup = \App\Models\UnitGroup::where('code', 'LENGTH')->first();
        if (!$lengthGroup) {
            app(\Database\Seeders\SystemLengthUnitsSeeder::class)->run();
            $lengthGroup = \App\Models\UnitGroup::where('code', 'LENGTH')->first();
        }
        $lengthUnits = $lengthGroup ? $lengthGroup->activeUnits()->select('id', 'name', 'short_code', 'is_base', 'ratio_to_base')->get() : \App\Models\Unit::all();

        return response()->json([
            'success' => true,
            'data' => [
                'auto_generated_code' => $autoGeneratedCode,
                'categories' => AdminManufacturingCategoryResource::collection($activeCategories),
                'fabric_widths' => $fabricWidths,
                'available_tasks' => $availableTasks,
                'subsidiary_raw_materials' => $subsidiaryMaterials,
                'stitching_raw_materials' => $stitchingMaterials,
                'packaging_raw_materials' => $packagingMaterials,
                'length_units' => $lengthUnits,
                'storefront_products' => $storefrontProducts,
                'storefront_combinations' => $storefrontCombinations,
            ],
        ]);
    }

    /**
     * Display details of a single manufacturing product.
     */
    public function show($id): JsonResponse
    {
        $product = ManufacturingProduct::with($this->withRelations)->findOrFail($id);

        return response()->json([
            'success' => true,
            'data' => new AdminManufacturingProductResource($product),
        ]);
    }

    /**
     * Store a newly created manufacturing product.
     */
    public function store(StoreManufacturingProductRequest $request): JsonResponse
    {
        $validated = $request->validated();

        return DB::transaction(function () use ($request, $validated) {
            $category = ManufacturingProductCategory::findOrFail($validated['manufacturing_product_category_id']);
            if (!$category->status) {
                throw ValidationException::withMessages([
                    'manufacturing_product_category_id' => ['The selected category is inactive. Products can only be linked to active categories.'],
                ]);
            }

            $imagePath = null;
            if ($request->hasFile('image')) {
                $imagePath = $request->file('image')->store('manufacturing_products', 'public');
            }

            $code = $validated['code'] ?? null;
            if (!$code) {
                $year = date('Y');
                $latest = ManufacturingProduct::where('code', 'like', "MP-{$year}-%")->latest('id')->first();
                $seq = 1;
                if ($latest) {
                    $parts = explode('-', $latest->code);
                    $seq = ((int) end($parts)) + 1;
                } else {
                    $latestId = ManufacturingProduct::max('id') ?? 0;
                    $seq = $latestId + 1;
                }
                $code = "MP-{$year}-" . str_pad($seq, 4, '0', STR_PAD_LEFT);
            }

            $isCommonSubsidiary = !isset($validated['is_common_subsidiary']) || (bool) $validated['is_common_subsidiary'];
            $isSubsidiaryUsed = !empty($validated['is_subsidiary_used']);
            $isStitchingUsed = !empty($validated['is_stitching_used']);

            $product = ManufacturingProduct::create([
                'name' => $validated['name'],
                'code' => $code,
                'manufacturing_product_category_id' => $validated['manufacturing_product_category_id'],
                'status' => $validated['status'] ?? 'active',
                'standard_labor_rate' => $validated['standard_labor_rate'] ?? 0.00,
                'image_path' => $imagePath,
                'is_fabric_used' => $validated['is_fabric_used'] ?? true,
                'standard_fabric_width' => $validated['standard_fabric_width'] ?? 44.00,
                'standard_fabric_length' => $validated['standard_fabric_length'] ?? 2.50,
                'fabric_width_unit' => $validated['fabric_width_unit'] ?? 'in',
                'fabric_length_unit' => $validated['fabric_length_unit'] ?? 'm',
                'is_common_subsidiary' => $isCommonSubsidiary,
                'is_subsidiary_used' => $isSubsidiaryUsed,
                'is_stitching_used' => $isStitchingUsed,
                'is_packaging_used' => false,
                'product_id' => $validated['product_id'] ?? null,
                'product_combination_id' => $validated['product_combination_id'] ?? null,
            ]);

            $this->syncProductRelationships($product, $validated);

            return response()->json([
                'success' => true,
                'message' => "Manufacturing Product {$product->name} created successfully!",
                'data' => new AdminManufacturingProductResource($product->fresh($this->withRelations)),
            ], 201);
        });
    }

    /**
     * Update an existing manufacturing product.
     */
    public function update(UpdateManufacturingProductRequest $request, $id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);
        $validated = $request->validated();

        return DB::transaction(function () use ($request, $product, $validated) {
            if (isset($validated['manufacturing_product_category_id'])) {
                $category = ManufacturingProductCategory::findOrFail($validated['manufacturing_product_category_id']);
                if (!$category->status) {
                    throw ValidationException::withMessages([
                        'manufacturing_product_category_id' => ['The selected category is inactive. Products can only be linked to active categories.'],
                    ]);
                }
            }

            $imagePath = $product->image_path;
            if ($request->hasFile('image')) {
                if ($imagePath && Storage::disk('public')->exists($imagePath)) {
                    Storage::disk('public')->delete($imagePath);
                }
                $imagePath = $request->file('image')->store('manufacturing_products', 'public');
            }

            $updateData = [];
            foreach (['name', 'code', 'manufacturing_product_category_id', 'status', 'standard_labor_rate', 'is_fabric_used', 'standard_fabric_width', 'standard_fabric_length', 'fabric_width_unit', 'fabric_length_unit', 'is_common_subsidiary', 'is_subsidiary_used', 'is_stitching_used', 'product_id', 'product_combination_id'] as $field) {
                if (array_key_exists($field, $validated)) {
                    $updateData[$field] = $validated[$field];
                }
            }
            if ($imagePath !== $product->image_path) {
                $updateData['image_path'] = $imagePath;
            }

            if (!empty($updateData)) {
                $product->update($updateData);
            }

            $this->syncProductRelationships($product, $validated);

            return response()->json([
                'success' => true,
                'message' => "Manufacturing Product {$product->name} updated successfully!",
                'data' => new AdminManufacturingProductResource($product->fresh($this->withRelations)),
            ]);
        });
    }

    /**
     * Toggle the status (active / inactive) of a manufacturing product.
     */
    public function toggleStatus($id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);
        $newStatus = ($product->status === 'active') ? 'inactive' : 'active';
        $product->update(['status' => $newStatus]);

        return response()->json([
            'success' => true,
            'message' => "Manufacturing Product {$product->name} status set to {$newStatus}.",
            'data' => [
                'id' => $product->id,
                'status' => $product->status,
                'status_label' => ucfirst($product->status),
            ],
        ]);
    }

    /**
     * Delete a manufacturing product.
     */
    public function destroy($id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);

        $jobsCount = DB::table('production_jobs')->where('manufacturing_product_id', $product->id)->count();
        $batchesCount = DB::table('production_batches')->where('manufacturing_product_id', $product->id)->count();

        if ($jobsCount > 0 || $batchesCount > 0 || $product->allocations()->exists()) {
            return response()->json([
                'success' => false,
                'message' => "Cannot delete manufacturing product [{$product->name}]: It is linked to {$jobsCount} production jobs, {$batchesCount} production batches, or active allocations.",
            ], 422);
        }

        $product->patterns()->delete();
        $product->subsidiaryMaterials()->detach();
        $product->stitchingMaterials()->detach();
        $product->tasks()->detach();
        $product->delete();

        return response()->json([
            'success' => true,
            'message' => "Manufacturing Product {$product->name} deleted successfully.",
        ]);
    }

    /**
     * Helper to sync relationships (subsidiary, stitching, patterns, task routing).
     */
    protected function syncProductRelationships(ManufacturingProduct $product, array $validated): void
    {
        // 1. Sync Common Subsidiary Materials
        $isCommonSubsidiary = array_key_exists('is_common_subsidiary', $validated) ? (bool)$validated['is_common_subsidiary'] : (bool)$product->is_common_subsidiary;
        $isSubsidiaryUsed = array_key_exists('is_subsidiary_used', $validated) ? (bool)$validated['is_subsidiary_used'] : (bool)$product->is_subsidiary_used;

        if ($isSubsidiaryUsed && $isCommonSubsidiary && !empty($validated['subsidiary_materials'])) {
            $syncSub = [];
            foreach ($validated['subsidiary_materials'] as $row) {
                if (!empty($row['raw_material_id'])) {
                    $syncSub[$row['raw_material_id']] = [
                        'consumption_quantity' => $row['consumption_quantity'],
                    ];
                }
            }
            $product->subsidiaryMaterials()->sync($syncSub);
        } elseif (!$isSubsidiaryUsed || !$isCommonSubsidiary) {
            $product->subsidiaryMaterials()->detach();
        }

        // 2. Sync Stitching Materials
        if (array_key_exists('stitching_materials', $validated)) {
            $stitchingIds = array_filter((array) $validated['stitching_materials']);
            $product->stitchingMaterials()->sync($stitchingIds);
        }

        // 3. Process Patterns
        $defaultWidth = FabricWidth::where('status', true)->first();
        $patternsData = $validated['patterns'] ?? null;

        if (is_array($patternsData) && count($patternsData) > 0) {
            $keptPatternIds = [];
            foreach ($patternsData as $pIndex => $pRow) {
                $isDefault = ($pIndex === 0);
                $firstW = $pRow['widths'][0] ?? null;
                $widthId = $firstW['fabric_width_id'] ?? $pRow['fabric_width_id'] ?? ($defaultWidth?->id);
                $length = $firstW['fabric_length'] ?? $pRow['fabric_length'] ?? 2.50;
                $lengthUnit = $firstW['fabric_length_unit'] ?? $pRow['fabric_length_unit'] ?? 'm';

                $patternModel = ManufacturingProductPattern::updateOrCreate(
                    [
                        'id' => $pRow['id'] ?? null,
                        'manufacturing_product_id' => $product->id,
                    ],
                    [
                        'name' => $pRow['name'] ?? ('Pattern ' . ($pIndex + 1)),
                        'fabric_width_id' => $widthId,
                        'fabric_length' => $length,
                        'fabric_length_unit' => $lengthUnit,
                        'standard_labor_rate' => $pRow['standard_labor_rate'] ?? $product->standard_labor_rate ?? 0.00,
                        'is_default' => $isDefault,
                        'is_subsidiary_used' => $isCommonSubsidiary ? $isSubsidiaryUsed : !empty($pRow['is_subsidiary_used']),
                    ]
                );

                $keptPatternIds[] = $patternModel->id;

                // Sync Pattern Fabric Widths
                $patternModel->patternFabricWidths()->delete();
                $widthsToInsert = !empty($pRow['widths']) ? $pRow['widths'] : [
                    ['fabric_width_id' => $widthId, 'fabric_length' => $length, 'fabric_length_unit' => $lengthUnit]
                ];
                foreach ($widthsToInsert as $wRow) {
                    if (!empty($wRow['fabric_width_id']) && isset($wRow['fabric_length'])) {
                        ManufacturingPatternFabricWidth::create([
                            'pattern_id' => $patternModel->id,
                            'fabric_width_id' => (int) $wRow['fabric_width_id'],
                            'fabric_length' => $wRow['fabric_length'],
                            'fabric_length_unit' => $wRow['fabric_length_unit'] ?? 'm',
                        ]);
                    }
                }

                // Sync Pattern Subsidiary Materials
                if ($isCommonSubsidiary) {
                    if ($isSubsidiaryUsed && !empty($validated['subsidiary_materials'])) {
                        $patternSubData = [];
                        foreach ($validated['subsidiary_materials'] as $subRow) {
                            if (!empty($subRow['raw_material_id'])) {
                                $patternSubData[$subRow['raw_material_id']] = [
                                    'consumption_quantity' => $subRow['consumption_quantity'],
                                ];
                            }
                        }
                        $patternModel->subsidiaryMaterials()->sync($patternSubData);
                    } else {
                        $patternModel->subsidiaryMaterials()->detach();
                    }
                } else {
                    if (!empty($pRow['is_subsidiary_used']) && !empty($pRow['subsidiary_materials'])) {
                        $patternSubData = [];
                        foreach ($pRow['subsidiary_materials'] as $subRow) {
                            if (!empty($subRow['raw_material_id'])) {
                                $patternSubData[$subRow['raw_material_id']] = [
                                    'consumption_quantity' => $subRow['consumption_quantity'],
                                ];
                            }
                        }
                        $patternModel->subsidiaryMaterials()->sync($patternSubData);
                    } else {
                        $patternModel->subsidiaryMaterials()->detach();
                    }
                }

                // Sync Pattern Tasks
                $taskSyncData = [];
                $validTasks = array_filter($pRow['tasks'] ?? [], fn($t) => !empty($t['task_id']));

                $hasFinal = false;
                foreach ($validTasks as $vt) {
                    if (!empty($vt['is_final_step'])) $hasFinal = true;
                }
                $lastTaskIndex = count($validTasks) - 1;

                $seq = 1;
                foreach (array_values($validTasks) as $idx => $tRow) {
                    $isFinal = $hasFinal ? !empty($tRow['is_final_step']) : ($idx === $lastTaskIndex);
                    $taskSeq = !empty($tRow['sequence_number']) ? (int) $tRow['sequence_number'] : $seq++;
                    $taskSyncData[$tRow['task_id']] = [
                        'sequence_number' => $taskSeq,
                        'standard_labor_rate' => array_key_exists('standard_labor_rate', $tRow) && $tRow['standard_labor_rate'] !== null && $tRow['standard_labor_rate'] !== '' ? $tRow['standard_labor_rate'] : ($product->standard_labor_rate ?? 0.00),
                        'is_final_step' => $isFinal,
                    ];
                }
                $patternModel->tasks()->sync($taskSyncData);

                // Sync default pattern tasks to product task pivot for legacy compatibility
                if ($isDefault) {
                    $product->tasks()->sync($taskSyncData);

                    // Update product standard fabric dimensions from default pattern
                    $matchedWidth = FabricWidth::find($widthId);
                    $product->update([
                        'standard_fabric_width' => $matchedWidth?->value ?? $product->standard_fabric_width,
                        'standard_fabric_length' => $length,
                        'fabric_width_unit' => $matchedWidth?->unit ?? $product->fabric_width_unit,
                        'fabric_length_unit' => $lengthUnit,
                    ]);
                }
            }

            // Remove deleted patterns
            ManufacturingProductPattern::where('manufacturing_product_id', $product->id)
                ->whereNotIn('id', $keptPatternIds)
                ->delete();
        } else {
            // Legacy task routing payload fallback
            if (array_key_exists('tasks', $validated) && is_array($validated['tasks'])) {
                $taskSyncData = [];
                $validTasks = array_filter($validated['tasks'], fn($t) => !empty($t['task_id']));

                $hasFinal = false;
                foreach ($validTasks as $vt) {
                    if (!empty($vt['is_final_step'])) $hasFinal = true;
                }
                $lastTaskIndex = count($validTasks) - 1;

                $seq = 1;
                foreach (array_values($validTasks) as $idx => $tRow) {
                    $isFinal = $hasFinal ? !empty($tRow['is_final_step']) : ($idx === $lastTaskIndex);
                    $taskSeq = !empty($tRow['sequence_number']) ? (int) $tRow['sequence_number'] : $seq++;
                    $taskSyncData[$tRow['task_id']] = [
                        'sequence_number' => $taskSeq,
                        'standard_labor_rate' => array_key_exists('standard_labor_rate', $tRow) && $tRow['standard_labor_rate'] !== null && $tRow['standard_labor_rate'] !== '' ? $tRow['standard_labor_rate'] : ($product->standard_labor_rate ?? 0.00),
                        'is_final_step' => $isFinal,
                    ];
                }
                $product->tasks()->sync($taskSyncData);

                // If product has no patterns, create default pattern "Standard Fold"
                if ($product->patterns()->count() === 0) {
                    $widthId = $defaultWidth?->id;
                    $length = $validated['standard_fabric_length'] ?? $product->standard_fabric_length ?? 2.50;
                    $lengthUnit = $validated['fabric_length_unit'] ?? $product->fabric_length_unit ?? 'm';

                    $pattern = ManufacturingProductPattern::create([
                        'manufacturing_product_id' => $product->id,
                        'name' => 'Standard Fold',
                        'fabric_width_id' => $widthId,
                        'fabric_length' => $length,
                        'fabric_length_unit' => $lengthUnit,
                        'standard_labor_rate' => $product->standard_labor_rate ?? 0.00,
                        'is_default' => true,
                        'is_subsidiary_used' => $isSubsidiaryUsed,
                    ]);

                    if ($widthId) {
                        ManufacturingPatternFabricWidth::create([
                            'pattern_id' => $pattern->id,
                            'fabric_width_id' => $widthId,
                            'fabric_length' => $length,
                            'fabric_length_unit' => $lengthUnit,
                        ]);
                    }

                    $pattern->tasks()->sync($taskSyncData);
                }
            }
        }
    }
}
