<?php

namespace App\Http\Controllers\Api\V1\Admin;

use App\Http\Controllers\Controller;
use App\Models\ManufacturingProduct;
use App\Models\ManufacturingProductCategory;
use App\Models\RawMaterial;
use App\Models\Task;
use App\Models\Product;
use App\Models\ProductCombination;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

class AdminManufacturingProductController extends Controller
{
    /**
     * Display a paginated list of manufacturing products.
     */
    public function index(Request $request): JsonResponse
    {
        $query = ManufacturingProduct::with([
            'category',
            'tasks',
            'subsidiaryMaterials',
            'stitchingMaterials',
            'packagingMaterials',
            'frontendProduct',
            'frontendCombination',
        ]);

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('code', 'like', "%{$search}%");
            });
        }

        if ($request->filled('category_id')) {
            $query->where('manufacturing_product_category_id', $request->input('category_id'));
        }

        if ($request->filled('status')) {
            $query->where('status', $request->input('status'));
        }

        $perPage = (int) $request->input('per_page', 15);
        $products = $query->latest('id')->paginate($perPage);

        return response()->json([
            'success' => true,
            'data' => $products->items(),
            'meta' => [
                'current_page' => $products->currentPage(),
                'last_page' => $products->lastPage(),
                'per_page' => $products->perPage(),
                'total' => $products->total(),
            ],
        ]);
    }

    /**
     * Get lookup options for creating/editing manufacturing products.
     */
    public function options(Request $request): JsonResponse
    {
        $activeCategories = ManufacturingProductCategory::where('status', true)->orderBy('name')->get();
        $availableTasks = Task::where('status', true)->orderBy('id')->get();

        $subsidiaryMaterials = RawMaterial::whereHas('category', fn($q) => $q->where('code', 'CAT-SUB'))
            ->where('status', true)
            ->orderBy('name')
            ->get();

        $stitchingMaterials = RawMaterial::whereHas('category', fn($q) => $q->where('code', 'CAT-STITCH'))
            ->where('status', true)
            ->orderBy('name')
            ->get();

        $packagingMaterials = RawMaterial::whereHas('category', fn($q) => $q->where('code', 'CAT-PKG'))
            ->where('status', true)
            ->orderBy('name')
            ->get();

        $storefrontProducts = Product::where('is_active', true)->select('id', 'title', 'sku')->orderBy('title')->get();

        $productId = $request->input('product_id');
        $storefrontCombinations = $productId
            ? ProductCombination::where('product_id', $productId)->where('is_active', true)->get()
            : collect();

        // Generate next sequential product code preview
        $year = date('Y');
        $latest = ManufacturingProduct::where('code', 'like', "MP-{$year}-%")->latest('id')->first();
        $seq = 1;
        if ($latest) {
            $parts = explode('-', $latest->code);
            $seq = ((int) end($parts)) + 1;
        } else {
            $latestId = ManufacturingProduct::max('id') ?? 0;
            $seq = $latestId + 1;
        }
        $autoGeneratedCode = "MP-{$year}-" . str_pad($seq, 4, '0', STR_PAD_LEFT);

        return response()->json([
            'success' => true,
            'data' => [
                'auto_generated_code' => $autoGeneratedCode,
                'categories' => $activeCategories,
                'available_tasks' => $availableTasks,
                'subsidiary_raw_materials' => $subsidiaryMaterials,
                'stitching_raw_materials' => $stitchingMaterials,
                'packaging_raw_materials' => $packagingMaterials,
                'storefront_products' => $storefrontProducts,
                'storefront_combinations' => $storefrontCombinations,
            ],
        ]);
    }

    /**
     * Display details of a single manufacturing product.
     */
    public function show($id): JsonResponse
    {
        $product = ManufacturingProduct::with([
            'category',
            'tasks',
            'subsidiaryMaterials',
            'stitchingMaterials',
            'packagingMaterials',
            'frontendProduct',
            'frontendCombination',
        ])->findOrFail($id);

        return response()->json([
            'success' => true,
            'data' => $product,
        ]);
    }

    /**
     * Store a newly created manufacturing product.
     */
    public function store(Request $request): JsonResponse
    {
        $validated = $this->validateProductData($request);

        return DB::transaction(function () use ($request, $validated) {
            $category = ManufacturingProductCategory::findOrFail($validated['manufacturing_product_category_id']);
            if (!$category->status) {
                throw ValidationException::withMessages([
                    'manufacturing_product_category_id' => ['The selected category is inactive. Products can only be linked to active categories.'],
                ]);
            }

            $imagePath = null;
            if ($request->hasFile('image')) {
                $imagePath = $request->file('image')->store('manufacturing_products', 'public');
            }

            $product = ManufacturingProduct::create([
                'name' => $validated['name'],
                'manufacturing_product_category_id' => $validated['manufacturing_product_category_id'],
                'status' => $validated['status'] ?? 'active',
                'standard_labor_rate' => $validated['standard_labor_rate'] ?? 15.00,
                'image_path' => $imagePath,
                'is_fabric_used' => $validated['is_fabric_used'] ?? false,
                'standard_fabric_width' => ($validated['is_fabric_used'] ?? false) ? $validated['standard_fabric_width'] : null,
                'standard_fabric_length' => ($validated['is_fabric_used'] ?? false) ? $validated['standard_fabric_length'] : null,
                'fabric_width_unit' => ($validated['is_fabric_used'] ?? false) ? $validated['fabric_width_unit'] : null,
                'fabric_length_unit' => ($validated['is_fabric_used'] ?? false) ? $validated['fabric_length_unit'] : null,
                'is_subsidiary_used' => $validated['is_subsidiary_used'] ?? false,
                'is_stitching_used' => $validated['is_stitching_used'] ?? false,
                'is_packaging_used' => $validated['is_packaging_used'] ?? false,
                'product_id' => $validated['product_id'] ?? null,
                'product_combination_id' => $validated['product_combination_id'] ?? null,
            ]);

            $this->syncRelationships($product, $validated);

            return response()->json([
                'success' => true,
                'message' => "Manufacturing Product {$product->name} created successfully!",
                'data' => $product->fresh(['category', 'tasks', 'subsidiaryMaterials', 'stitchingMaterials', 'packagingMaterials']),
            ], 201);
        });
    }

    /**
     * Update an existing manufacturing product.
     */
    public function update(Request $request, $id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);
        $validated = $this->validateProductData($request, $product->id);

        return DB::transaction(function () use ($request, $product, $validated) {
            $category = ManufacturingProductCategory::findOrFail($validated['manufacturing_product_category_id']);
            if (!$category->status) {
                throw ValidationException::withMessages([
                    'manufacturing_product_category_id' => ['The selected category is inactive. Products can only be linked to active categories.'],
                ]);
            }

            $imagePath = $product->image_path;
            if ($request->hasFile('image')) {
                if ($imagePath && Storage::disk('public')->exists($imagePath)) {
                    Storage::disk('public')->delete($imagePath);
                }
                $imagePath = $request->file('image')->store('manufacturing_products', 'public');
            }

            $product->update([
                'name' => $validated['name'],
                'manufacturing_product_category_id' => $validated['manufacturing_product_category_id'],
                'status' => $validated['status'] ?? 'active',
                'standard_labor_rate' => $validated['standard_labor_rate'] ?? 15.00,
                'image_path' => $imagePath,
                'is_fabric_used' => $validated['is_fabric_used'] ?? false,
                'standard_fabric_width' => ($validated['is_fabric_used'] ?? false) ? $validated['standard_fabric_width'] : null,
                'standard_fabric_length' => ($validated['is_fabric_used'] ?? false) ? $validated['standard_fabric_length'] : null,
                'fabric_width_unit' => ($validated['is_fabric_used'] ?? false) ? $validated['fabric_width_unit'] : null,
                'fabric_length_unit' => ($validated['is_fabric_used'] ?? false) ? $validated['fabric_length_unit'] : null,
                'is_subsidiary_used' => $validated['is_subsidiary_used'] ?? false,
                'is_stitching_used' => $validated['is_stitching_used'] ?? false,
                'is_packaging_used' => $validated['is_packaging_used'] ?? false,
                'product_id' => $validated['product_id'] ?? null,
                'product_combination_id' => $validated['product_combination_id'] ?? null,
            ]);

            $this->syncRelationships($product, $validated);

            return response()->json([
                'success' => true,
                'message' => "Manufacturing Product {$product->name} updated successfully!",
                'data' => $product->fresh(['category', 'tasks', 'subsidiaryMaterials', 'stitchingMaterials', 'packagingMaterials']),
            ]);
        });
    }

    /**
     * Toggle the status (active / inactive) of a manufacturing product.
     */
    public function toggleStatus($id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);
        $newStatus = ($product->status === 'active') ? 'inactive' : 'active';
        $product->update(['status' => $newStatus]);

        return response()->json([
            'success' => true,
            'message' => "Manufacturing Product {$product->name} status set to {$newStatus}.",
            'data' => [
                'id' => $product->id,
                'status' => $product->status,
            ],
        ]);
    }

    /**
     * Delete a manufacturing product.
     */
    public function destroy($id): JsonResponse
    {
        $product = ManufacturingProduct::findOrFail($id);

        // Check if attached to existing production jobs or batches
        $jobsCount = DB::table('production_jobs')->where('manufacturing_product_id', $product->id)->count();
        $batchesCount = DB::table('production_batches')->where('manufacturing_product_id', $product->id)->count();

        if ($jobsCount > 0 || $batchesCount > 0) {
            return response()->json([
                'success' => false,
                'message' => "Cannot delete manufacturing product [{$product->name}]: It is linked to {$jobsCount} production jobs and {$batchesCount} production batches.",
            ], 422);
        }

        $product->delete();

        return response()->json([
            'success' => true,
            'message' => "Manufacturing Product {$product->name} deleted successfully.",
        ]);
    }

    /**
     * Helper to validate product request payload.
     */
    protected function validateProductData(Request $request, $productId = null): array
    {
        $rules = [
            'name' => 'required|string|max:255',
            'manufacturing_product_category_id' => 'required|exists:manufacturing_product_categories,id',
            'status' => 'nullable|in:active,inactive',
            'standard_labor_rate' => 'nullable|numeric|min:0',
            'image' => 'nullable|image|max:10240',
            'is_fabric_used' => 'nullable|boolean',
            'standard_fabric_width' => 'required_if:is_fabric_used,true,1|nullable|numeric|min:0.01',
            'standard_fabric_length' => 'required_if:is_fabric_used,true,1|nullable|numeric|min:0.01',
            'fabric_width_unit' => 'required_if:is_fabric_used,true,1|nullable|in:inch,cm',
            'fabric_length_unit' => 'required_if:is_fabric_used,true,1|nullable|in:meter,yard',
            'is_subsidiary_used' => 'nullable|boolean',
            'subsidiary_materials' => 'required_if:is_subsidiary_used,true,1|nullable|array',
            'subsidiary_materials.*.raw_material_id' => 'required_with:subsidiary_materials|exists:raw_materials,id',
            'subsidiary_materials.*.consumption_quantity' => 'required_with:subsidiary_materials|numeric|min:0.0001',
            'is_stitching_used' => 'nullable|boolean',
            'stitching_materials' => 'nullable|array',
            'stitching_materials.*' => 'exists:raw_materials,id',
            'is_packaging_used' => 'nullable|boolean',
            'packaging_materials' => 'required_if:is_packaging_used,true,1|nullable|array',
            'packaging_materials.*.raw_material_id' => 'required_with:packaging_materials|exists:raw_materials,id',
            'packaging_materials.*.required_quantity' => 'required_with:packaging_materials|numeric|min:0.0001',
            'tasks' => 'required|array|min:1',
            'tasks.*.task_id' => 'required|exists:tasks,id',
            'tasks.*.sequence_number' => 'nullable|integer|min:1',
            'tasks.*.standard_labor_rate' => 'nullable|numeric|min:0',
            'tasks.*.is_final_step' => 'nullable|boolean',
            'product_id' => 'nullable|exists:products,id',
            'product_combination_id' => 'nullable|exists:product_combinations,id',
        ];

        $validated = $request->validate($rules);

        // Validate unique subsidiary materials
        if (!empty($validated['is_subsidiary_used']) && !empty($validated['subsidiary_materials'])) {
            $subIds = array_column($validated['subsidiary_materials'], 'raw_material_id');
            if (count($subIds) !== count(array_unique($subIds))) {
                throw ValidationException::withMessages([
                    'subsidiary_materials' => ['Duplicate subsidiary materials selected. Each material must only appear once.'],
                ]);
            }
        }

        // Validate unique packaging materials
        if (!empty($validated['is_packaging_used']) && !empty($validated['packaging_materials'])) {
            $pkgIds = array_column($validated['packaging_materials'], 'raw_material_id');
            if (count($pkgIds) !== count(array_unique($pkgIds))) {
                throw ValidationException::withMessages([
                    'packaging_materials' => ['Duplicate packaging materials selected. Each material must only appear once.'],
                ]);
            }
        }

        // Validate task routing rules
        $taskIds = array_column($validated['tasks'], 'task_id');
        if (count($taskIds) !== count(array_unique($taskIds))) {
            throw ValidationException::withMessages([
                'tasks' => ['Duplicate tasks found in routing sequence. Each task can only appear once.'],
            ]);
        }

        // Normalize final step
        $finalStepCount = 0;
        foreach ($validated['tasks'] as $tRow) {
            if (!empty($tRow['is_final_step'])) {
                $finalStepCount++;
            }
        }

        if ($finalStepCount !== 1) {
            $lastIdx = count($validated['tasks']) - 1;
            foreach ($validated['tasks'] as $i => &$tRow) {
                $tRow['is_final_step'] = ($i === $lastIdx);
            }
        }

        return $validated;
    }

    /**
     * Helper to sync pivot relationships for materials and task routing.
     */
    protected function syncRelationships(ManufacturingProduct $product, array $validated): void
    {
        // Sync Subsidiary Materials
        if (!empty($validated['is_subsidiary_used']) && !empty($validated['subsidiary_materials'])) {
            $syncSub = [];
            foreach ($validated['subsidiary_materials'] as $row) {
                $syncSub[$row['raw_material_id']] = [
                    'consumption_quantity' => $row['consumption_quantity'],
                ];
            }
            $product->subsidiaryMaterials()->sync($syncSub);
        } else {
            $product->subsidiaryMaterials()->detach();
        }

        // Sync Stitching Materials
        if (!empty($validated['is_stitching_used']) && !empty($validated['stitching_materials'])) {
            $product->stitchingMaterials()->sync($validated['stitching_materials']);
        } else {
            $product->stitchingMaterials()->detach();
        }

        // Sync Packaging Materials
        if (!empty($validated['is_packaging_used']) && !empty($validated['packaging_materials'])) {
            $syncPkg = [];
            foreach ($validated['packaging_materials'] as $row) {
                $syncPkg[$row['raw_material_id']] = [
                    'required_quantity' => $row['required_quantity'],
                ];
            }
            $product->packagingMaterials()->sync($syncPkg);
        } else {
            $product->packagingMaterials()->detach();
        }

        // Sync Task Routing Sequence
        $taskSync = [];
        $baseRate = $validated['standard_labor_rate'] ?? $product->standard_labor_rate ?? 15.00;
        foreach ($validated['tasks'] as $idx => $tRow) {
            $seq = !empty($tRow['sequence_number']) ? (int) $tRow['sequence_number'] : ($idx + 1);
            $taskSync[$tRow['task_id']] = [
                'sequence_number' => $seq,
                'standard_labor_rate' => !empty($tRow['standard_labor_rate']) ? $tRow['standard_labor_rate'] : $baseRate,
                'is_final_step' => !empty($tRow['is_final_step']),
            ];
        }

        $product->tasks()->sync($taskSync);
    }
}
